# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 1

[[main]]
  name = "Présentation"
  url = "presentation/"
  weight = 2

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 3

# [[main]]
#    name = "Posts"
#    url = "#posts"
#    weight = 20

# [[main]]
#   name = "Projects"
#   url = "#project"
#   weight = 30

# [[main]]
#   name = "Publications"
#   url = "#featured"
#   weight = 40


[[main]]
  name = "Tableaux"
  url = "tableaux/"
  weight = 4


[[main]]
  name = "Nuage de mots"
  url = "nuage/"
  weight = 5

[[main]]
  name = "iTrameur"
  url = "itrameur/"
  weight = 6

[[main]]
  name = "Scripts"
  url = "scripts/"
  weight = 7


# [[courses]]
#   name = "Overview"
#   weight = 1
#   url = "/courses/"

[[courses]]
  name = "Blog"
  weight = 11
  identifier = "blog"

[[main_right]]
  name = "<i class=\"fab fa-github-alt\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://github.com/xingyuliuNLP/projet_encadre"
  weight = 1

# [[main]]
#   name = "Tableaux"
#   url = "test/"
#   weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
